# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'docker.io'
  dockerRegistryServiceConnection: 'a60699dd-9988-4a46-b728-e8bf03784aa8'
  imageRepository: 'alexandershabunevich/nginx'

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/nginx/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: variabledehydration@0
      inputs:
        prefixes: 'GITVERSION,BUILD'
        outpath: '$(Build.ArtifactStagingDirectory)'